<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Rorrim.Client</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.21" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.21" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.21" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.21" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.21" />
    <PackageReference Include="Grpc.Net.Client" Version="2.83.0" />
    <PackageReference Include="Google.Protobuf" Version="3.36.1" />
    <PackageReference Include="SkiaSharp" Version="3.119.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rorrim.Shared\Rorrim.Shared.csproj" />
    <ProjectReference Include="..\Rorrim.Codecs\Rorrim.Codecs.csproj" />
  </ItemGroup>

</Project>
